version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic.J2735BsmFilteredJson:1:1,topic.J2735BsmRawJson:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ppm:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - kafka
    links:
      - kafka
